// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAg0RTJ0txndHpL4wk8HiQ6UltuSAqYqu8',
    appId: '1:451240697870:web:4349b8f7d35eaa6a335c5f',
    messagingSenderId: '451240697870',
    projectId: 'crudapp-a2f01',
    authDomain: 'crudapp-a2f01.firebaseapp.com',
    storageBucket: 'crudapp-a2f01.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDM5D62xj-OEn-EVoVfrVq4vKdA9MS1OoQ',
    appId: '1:451240697870:android:73c749981520712e335c5f',
    messagingSenderId: '451240697870',
    projectId: 'crudapp-a2f01',
    storageBucket: 'crudapp-a2f01.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSPb0Kx2SMclVHLriXr_RoE9a4TiwS3Wc',
    appId: '1:451240697870:ios:1de415056583fca7335c5f',
    messagingSenderId: '451240697870',
    projectId: 'crudapp-a2f01',
    storageBucket: 'crudapp-a2f01.appspot.com',
    iosBundleId: 'com.example.crudApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSPb0Kx2SMclVHLriXr_RoE9a4TiwS3Wc',
    appId: '1:451240697870:ios:1de415056583fca7335c5f',
    messagingSenderId: '451240697870',
    projectId: 'crudapp-a2f01',
    storageBucket: 'crudapp-a2f01.appspot.com',
    iosBundleId: 'com.example.crudApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAg0RTJ0txndHpL4wk8HiQ6UltuSAqYqu8',
    appId: '1:451240697870:web:996cef28394848ed335c5f',
    messagingSenderId: '451240697870',
    projectId: 'crudapp-a2f01',
    authDomain: 'crudapp-a2f01.firebaseapp.com',
    storageBucket: 'crudapp-a2f01.appspot.com',
  );
}
